# Generated by Django 3.1.7 on 2021-05-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sending', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendemailmodel',
            name='message',
            field=models.CharField(default='Hello!', max_length=500),
        ),
    ]
