# Generated by Django 3.1.7 on 2021-05-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sending', '0002_sendemailmodel_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendemailmodel',
            name='file',
            field=models.FileField(default='files/LINEAR-ALGEBRA.pdf', upload_to=''),
        ),
    ]
